Contagem de Palavras

In [4]:
#Contagem de Palavras
from collections import Counter

sentence = "Este é um exemplo de contagem de palavras"
words = sentence.split()

word_count = Counter(words)

print(word_count)


Counter({'de': 2, 'Este': 1, 'é': 1, 'um': 1, 'exemplo': 1, 'contagem': 1, 'palavras': 1})


Multiplicação de Matrizes

In [6]:
#Multiplicação de Matrizes (função dot)
# Para multiplicar é necessário que o número de colunas de uma matriz seja igual ao número de linhas da outra

import numpy as np

matrix_a = np.array([[1,2], [3,4]])
matrix_b = np.array([[5,6], [7,8]])

result = np.dot(matrix_a, matrix_b)
result

array([[19, 22],
       [43, 50]])

In [8]:
#Multiplicação de Matrizes de 1 dimensão (função dot)
# Para multiplicar é necessário que o número de colunas de uma matriz seja igual ao número de linhas da outra

import numpy as np

matrix_a = np.array([1,2,3])
matrix_b = np.array([4,5,6])

result = np.dot(matrix_a, matrix_b)
result

32

In [9]:
#Multiplicação de Matrizes de 2 dimensões (função dot)
# Para multiplicar é necessário que o número de colunas de uma matriz seja igual ao número de linhas da outra

import numpy as np

matrix_a = np.array([[1,2], [3,4]])
matrix_b = np.array([[5,6], [7,8]])

result = np.dot(matrix_a, matrix_b)
result

array([[19, 22],
       [43, 50]])

In [10]:
#Multiplicação de matrizes por um escalar

import numpy as np

matrix_a = np.array([[1,2], [3,4]])
scalar = 5

result = np.dot(matrix_a, scalar)
result


array([[ 5, 10],
       [15, 20]])

In [11]:
#Multiplicação de matrizes de diferentes dimensões

import numpy as np

matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

result = np.dot(matrix_a, matrix_b)
result


array([[ 58,  64],
       [139, 154]])